### ISSUE TITLE
Plugin installs but doesnt work

### ISSUE THREAD

**Issue by simonedstrom96** [enfuse/backstage-chatgpt-plugin#5]
I have installed the plugin according to instructions, including the api key, and no errors are showing in vscode. When starting backstage locally with "yarn dev" i can access the frontend through the /chatgpt endpoint but when i make a request i receive the error seen in the image below. I tried installing cors as a fix in the backend but that did not fix it.

![image](https://github.com/enfuse/backstage-chatgpt-plugin/assets/42982214/6525d991-e398-4acf-ac27-e8ce35dd7982)

**Comment by FaisalAldarees** [comment]
Same here. Any advice?

**Comment by FaisalAldarees** [comment]
Just fixed it, make sure you have the latest version of the frontend/backend plugins.

**Comment by willoh1998** [comment]
@simonedstrom96 

Apologies for the late reply, were you able to get the plugin working?

**Comment by Jim-Gloaguen** [comment]
I am having the exact same error when making a request after trying to install the plugin today. Following @FaisalAldarees comment, I checked the plugins versions but they seem to be the latest with both at 1.1.1.
Tried on Firefox and Chrome, same result by the way.
Any ideas on how to fix ?

**Comment by willoh1998** [comment]
@Jim-Gloaguen 
Hi Jim! I am currently unable to replicate your issue, could you walk me through the steps you took in order to install the plugin?
